---
driver:
  name: vagrant
  network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
     - recipe[apt]

suites:
  - name: cicd
    run_list:
    - recipe[python]
    - recipe[jtalks::cicd]
    - recipe[java]
  - name: jcommune
    run_list:
    - recipe[ark]
    - recipe[mysql::server]
    - recipe[java]
    - recipe[jtalks::jcommune]
  - name: firewall
    run_list:
    - recipe[firewall]
    - recipe[jtalks::firewall]
  - name: nginx
    run_list:
    - recipe[nginx]
    - recipe[jtalks::nginx]