---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
     - recipe[apt]

suites:
  - name: cicd
    run_list:
    - recipe[python]
    - recipe[jtalks::cicd]
    - recipe[java]
  - name: jcommune
    run_list:
    - recipe[ark]
    - recipe[mysql::server]
    - recipe[java]
    - recipe[jtalks::jcommune]
  - name: firewall
    run_list:
    - recipe[firewall]
    - recipe[jtalks::firewall]