---
driver:
  name: vagrant
  network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    run_list:
     - recipe[apt]

busser:
  version: busser@0.6.2

suites:
  - name: cicd
    run_list:
    - recipe[build-essential]
    - recipe[python]
    - recipe[jtalks::cicd]
    - recipe[java]
  - name: databases
    run_list:
    - recipe[mysql::server]
    - recipe[database::mysql]
    - recipe[jtalks::databases]
  - name: nginx
    run_list:
    - recipe[nginx]
    - recipe[jtalks::nginx]
  - name: webapps
    run_list:
    - recipe[ark]
    - recipe[jtalks::webapps]
  - name: system
    run_list:
    - recipe[python]
    - recipe[java]
    - recipe[ark]
    - recipe[mysql::server]
    - recipe[database::mysql]
    - recipe[firewall]
    - recipe[nginx]
    - recipe[jtalks::cicd]
    - recipe[jtalks::firewall]
    - recipe[jtalks::webapps]
    - recipe[jtalks::databases]
    - recipe[jtalks::nginx]