---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
     - recipe[apt]

suites:
  - name: all
    run_list:
    - recipe[python]
    - recipe[mysql::server]
    - recipe[jtalks::cicd]
    - recipe[jtalks::jcommune]
